release:
  title-prefix: 'Nenki Offline '
  body-title: Changelog
  initial-version: 0.0.1
  tag-prefix: v
  pull-request-commit: include_merge_commit_only

branch:
  base-branch: main
  create-major-version-branch: false
  bump-version-commit-prefix: '@'

categories:
  - title: Breaking Changes
    commits:
      - ':boom:'
      - ':building_construction:'

  - title: Experimental Changes
    commits:
      - ':alembic:'

  - title: New features
    commits:
      - ':sparkles:'

  - title: Fixes
    commits:
      - ':bug:'
      - ':ambulance:'
      - ':lock:'
      - ':rotating_light:'
      - ':pencil2:'
      - ':adhesive_bandage:'

  - title: UI Changes
    commits:
      - ':lipstick:'
      - ':closed_lock_with_key:'
      - ':globe_with_meridians:'
      - ':bento:'
      - ':wheelchair:'
      - ':speech_balloon:'
      - ':children_crossing:'
      - ':iphone:'
      - ':egg:'
      - ':dizzy:'

  - title: Code Changes
    commits:
      - ':art:'
      - ':zap:'
      - ':fire:'
      - ':chart_with_upwards_trend:'
      - ':recycle:'
      - ':wrench:'
      - ':package:'
      - ':alien:'
      - ':truck:'
      - ':page_facing_up:'
      - ':card_file_box:'
      - ':bulb:'
      - ':mag:'
      - ':label:'
      - ':seedling:'
      - ':triangular_flag_on_post:'
      - ':goal_net:'
      - ':wastebasket:'
      - ':passport_control:'
      - ':coffin:'
      - ':necktie:'
      - ':stethoscope:'
      - ':bricks:'
      - ':thread:'
      - ':safety_vest:'

  - title: Documents
    commits:
      - ':memo:'

  - title: Dependencies
    commits:
      - ':arrow_down:'
      - ':arrow_up:'
      - ':pushpin:'
      - ':heavy_plus_sign:'
      - ':heavy_minus_sign:'

  - title: Tests / CI
    commits:
      - ':white_check_mark:'
      - ':green_heart:'
      - ':construction_worker:'
      - ':clown_face:'
      - ':test_tube:'

  - title: Development
    commits:
      - ':wrench:'
      - ':loud_sound:'
      - ':mute:'
      - ':see_no_evil:'
      - ':camera_flash:'
      - ':monocle_face:'
      - ':technologist:'

  - title: Branch Related Changes
    commits:
      - ':rewind:'
      - ':twisted_rightwards_arrows:'

  - title: Others
    commits:
      - ':rocket:'
      - ':tada:'
      - ':bookmark:'
      - ':construction:'
      - ':poop:'
      - ':beers:'
      - ':busts_in_silhouette:'
      - ':money_with_wings:'

files:
  - file-path: package.json
    line: 4

  - file-path: package-lock.json
    line: 3
