name: Build, Export, Deploy Next.js app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install npm packages
        run: npm ci --no-progress --no-audit

      - name: Build
        run: npm run build
        env:
          URL_PREFIX: ${{ github.event.repository.name }}

      - name: Export
        run: npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
        if: github.event_name != 'pull_request'
